package erpsollog.erpsollogmodel.erpsolloginvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 14 19:30:31 PKT 2021
// ---------------------------------------------------------------------
public interface SysUsersView extends ViewObject {
    String doERPSolutionLogin(String pUserCode, String pUserassword);
}

