package erpsollog.erpsollogmodel.erpsolloginvo;

import erpsollog.erpsollogmodel.erpsolloginvo.common.SysUsersView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 14 19:26:37 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysUsersViewImpl extends ViewObjectImpl implements SysUsersView {
    /**
     * This is the default constructor (do not remove).
     */
    public SysUsersViewImpl() {
    }
    public String doERPSolutionLogin(String pUserCode, String pUserassword) {
        setWhereClause("Userid ='"+pUserCode+"' AND Password='"+pUserassword+"'");
        executeQuery();
        if (getRowCount()>0) {
            return "ERPSOLYES";
       }
        return "NO";
    }
}

